// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using stavinskaya_darya_kt_41_20.Data;

#nullable disable

namespace stavinskaya_darya_kt_41_20.Migrations
{
    [DbContext(typeof(DisciplineDbContext))]
    [Migration("20231119123656_createDB")]
    partial class createDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("stavinskaya_darya_kt_41_20.Models.Direction", b =>
                {
                    b.Property<int>("DirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("direction_id")
                        .HasComment("Идентификатор направления");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DirectionId"));

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_direction_name")
                        .HasComment("Наименование направления");

                    b.HasKey("DirectionId")
                        .HasName("pk_(TableName)_DirectionId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("stavinskaya_darya_kt_41_20.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id")
                        .HasComment("Идентификатор дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_discipline_name")
                        .HasComment("Наименование дисциплины");

                    b.Property<bool>("DoesExist")
                        .HasColumnType("bool")
                        .HasColumnName("c_discipline_doesexist")
                        .HasComment("Существует ли дисциплина");

                    b.HasKey("DisciplineId")
                        .HasName("pk_(TableName)_DisciplineId");

                    b.HasIndex(new[] { "DirectionId" }, "idx_Discipline_fk_f_direction_id");

                    b.ToTable("Discipline", (string)null);
                });

            modelBuilder.Entity("stavinskaya_darya_kt_41_20.Models.Discipline", b =>
                {
                    b.HasOne("stavinskaya_darya_kt_41_20.Models.Direction", "Direction")
                        .WithMany("Disciplines")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_direction_id");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("stavinskaya_darya_kt_41_20.Models.Direction", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
